---

# Site
site_name: Docker containers
site_description: Custom built docker container
site_author: accesspc (Github Organization)
site_url: https://accesspc.github.io/containers/
copyright: <p>&copy <a href="https://github.com/accesspc"><em>Robertas Reiciunas</em> @accesspc</a><br/><span>This project is licensed under the GPL-3.0 license.</span></p>

# Project
repo_name: containers
repo_url: https://github.com/accesspc/containers

docs_dir: docs/content/

# mkdocs-material theme
theme:
  name: material
  # custom_dir: docs/overrides/
  favicon: assets/img/docker-mark-blue.svg
  features:
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - navigation.expand
    # - navigation.instant
    - navigation.tabs
    # - navigation.top
  icon:
    repo: fontawesome/brands/github
  logo: assets/img/docker-mark-blue.svg
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/eye
        name: Dark mode
    - media: '(prefers-color-scheme: light)'
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/eye-outline
        name: Light mode

markdown_extensions:
  - pymdownx.superfences
  - toc:
      anchorlink: true

# Plugins
plugins:
  - minify:
      minify_html: true

# Navigation
nav:
  - Home: index.md
  - Containers:
      - containers/mkdocs-material.md
